modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/StellarWind22/Fabric-Shield-Lib/issues"
license = "LGPL 2.1"

[[mods]]
modId = "shieldlib"
version = "${version}"
displayName = "ShieldLib"
authors = "StellarWind22, CringeStar, Rikka0w0, LegibleSleet827, RDKRACZ, Jamalam360, NLxDodge, Spaceman, How-Bout-No, Draylar, ggtylerr, kanpov, LimonBlaze, Luligabi1, ExDrill, muhammedesadcomert, timoreo22, OverLordsIII, SKZGx, Starexify"
description = '''
Library that makes it easy to add shields with full banner & enchantment support without conflictions!
'''
logoFile = "shieldlib.png"

[[dependencies.shieldlib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shieldlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shieldlib]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "shieldlib.mixins.json"
